library(corrplot)
mydata = read.csv("diff_heat.csv")
setEPS()
postscript("diff_heat.eps",width=18,height=8)
#jpeg("diff_heat.jpg",width=5000,height=5000)
corrplot(as.matrix(mydata), is.corr = FALSE, method = "circle",number.cex= 20/ncol(mydata),tl.cex=1.5,cl.cex=1.5,addCoef.col = "black",cl.lim = c(-100, 100),col=colorRampPalette(c("red","white","#27b500"))(200))
mtext("Rules",cex=2)
mtext("Training configurations",side=2,cex=2)
mtext("Score (%)",adj=0.975,cex=2,line=-2)
dev.off()
