library(corrplot)
mydata = read.csv("pre_rl_heat.csv")
setEPS()
postscript("pre_rl_heat.eps",width=18,height=4)
#jpeg("pre_rl_heat.jpg",width=5000,height=5000)
corrplot(as.matrix(mydata), is.corr = FALSE, method = "circle",addCoef.col = "black",number.cex= 20/ncol(mydata),tl.cex=1.5,cl.cex=1.5,cl.lim = c(0, 100),col=colorRampPalette(c("#8200a3","white","#0072ff"))(200))
mtext("Rules",cex=2)
mtext("Training\nconfigurations",side=2,cex=2,adj=0.25)
mtext("Score (%)",adj=0.97,cex=2,line=-2)
dev.off()
